language: node_js
node_js:
    - "0.11"
    - "0.10"
deploy:
    provider: npm
    email: izaakschroeder@aelatis.com
    api_key:
        secure: "GNrEbjA5um4A8IbHgt+RkigM1m/kELmHb2xW0Huw//C2vTgMwiNNTGJkBYHIIipA76G4sW/PO2lcf5sQ3bSCCIXIU0XPF1KSqNffufhqLcOeGJmKmxWvHCkJIFj7H2cRkKR0rL8CSsaJ6zIU7g/1/5PvpvKsw7LXAgqX/AedPhs="
    on:
        tags: true
        branch: master
